/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import database.User;
import java.awt.Color;

import java.sql.*;

/**
 *
 * @author m1cr0xf7
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    
    public Connection conn;
    
    public LoginPanel() {
        initComponents();
    }
    
    public LoginPanel(Connection conn) {
        this.conn = conn;
        initComponents();
    }
    
    public void setConnection(Connection conn) {
        this.conn = conn;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        logregLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        loginStatus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        accountStatusLabel = new javax.swing.JLabel();
        accountLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameInputActionPerformed(evt);
            }
        });
        add(usernameInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 209, 224, -1));

        passwordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputActionPerformed(evt);
            }
        });
        add(passwordInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 250, 224, -1));

        logregLabel.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        logregLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logregLabel.setText("Login / Register");
        add(logregLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 163, 289, -1));

        jLabel3.setText("Username");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 212, -1, -1));

        jLabel2.setText("Password");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 253, 59, -1));

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        add(registerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 291, 146, -1));

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 291, 137, -1));

        loginStatus.setForeground(new java.awt.Color(255, 51, 51));
        loginStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(loginStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 125, 365, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        accountStatusLabel.setText("Guest");
        add(accountStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, -1));

        accountLabel.setText("Account Status: ");
        add(accountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void usernameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameInputActionPerformed

    private void passwordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        String username = usernameInput.getText();
        String password = passwordInput.getText();
        
        User usr = new User(username, password);
        int ok;
        ok = usr.AddUser(this.conn);
        
        if (ok != -1){
            loginStatus.setText("Registered Successfuly");
            loginStatus.setForeground(Color.GREEN);
            accountStatusLabel.setText(username);
        } else {
            loginStatus.setText("Error adding user");
            loginStatus.setForeground(Color.RED);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameInput.getText();
        String password = passwordInput.getText();
        
        User user = new User(username, password);
        
        if (!(user.ValidLogin(conn, user))) {
            loginStatus.setForeground(Color.red);
            loginStatus.setText("Login is unsuccessful");
            return;
        }
        
        loginStatus.setText("Login is successful");
        loginStatus.setForeground(Color.GREEN);
        accountStatusLabel.setText(username);
        
        ListViewPanel.setUser(new User(username, password));
        BookPanel.setUser(new User(username, password));        
        
        // enable functionality that are exclusive only to admin
        ListViewPanel.adminMode();
        BookPanel.adminMode();
        BookEditPanel.adminMode();
        
        System.out.println(username + " - "+ password);
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountLabel;
    private javax.swing.JLabel accountStatusLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginStatus;
    private javax.swing.JLabel logregLabel;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField usernameInput;
    // End of variables declaration//GEN-END:variables
}
