/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Dimension;
import java.sql.*;

/**
 *
 * @author m1cr0xf7
 */
public class MasterFrame extends javax.swing.JFrame {

    /**
     * Creates new form MasterFrame
     */
    
    public final int     WIDTH = 800;
    public final int     HEIGHT = 500;
    public final int     MIN_WIDTH = 400;
    public final int     MIN_HEIGHT = 400;
    public final String TITLE = "E-Book Store Database";
    public Connection conn;
    
    public MasterFrame(Connection conn) {
        initComponents();
        setTitle(TITLE);
        setPreferredSize(new Dimension(WIDTH, HEIGHT));
        setMinimumSize(new Dimension(MIN_WIDTH, MIN_HEIGHT));
        this.conn = conn;
        
        // add database connection
        loginPanel1.setConnection(conn);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        welcomePanel1 = new gui.WelcomePanel();
        loginPanel1 = new gui.LoginPanel();
        listViewPanel1 = new gui.ListViewPanel();
        bookPanel1 = new gui.BookPanel();
        bookViewPanel1 = new gui.BookViewPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.addTab("Search", welcomePanel1);

        loginPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jTabbedPane2.addTab("Login", loginPanel1);
        jTabbedPane2.addTab("List Books", listViewPanel1);
        jTabbedPane2.addTab("Add Book", bookPanel1);
        jTabbedPane2.addTab("View Book", bookViewPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.BookPanel bookPanel1;
    private gui.BookViewPanel bookViewPanel1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private gui.ListViewPanel listViewPanel1;
    private gui.LoginPanel loginPanel1;
    private gui.WelcomePanel welcomePanel1;
    // End of variables declaration//GEN-END:variables
}
